version: "3"

services:
  redis:
    image: redis:6.2
    container_name: redis-toy-project-7
    ports:
      - 6379:6379
    restart: always
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq-toy-project-7
    ports:
      - 5672:5672
      - 15672:15672
    environment: 
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest